/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as _0xbfa6bd48a5dac421fc20390d3909ce7a8ddce08d0a020cb907e390f33319c7b0 from './0xbfa6bd48a5dac421fc20390d3909ce7a8ddce08d0a020cb907e390f33319c7b0.js'
